version: '2'
services:
  mongodb:
    image: 496323866215.dkr.ecr.eu-west-1.amazonaws.com/national/np-mongodb:latest
    hostname: "np-mongodb"
  national-parks:
    image: 496323866215.dkr.ecr.eu-west-1.amazonaws.com/national/national-parks:latest
    ports:
      - 8080:8080
      - 9631:9631
    links:
      - mongodb
    command: --peer mongodb --bind database:np-mongodb.default -u https://bldr.habitat.sh --channel stable -s at-once
